name = "scaffold-watch-recommender"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
# TMDB_API_KEY and ADMIN_KEY set via wrangler secret / .dev.vars

[[kv_namespaces]]
binding = "DATA"
id = "0415ef060eb84655acebe5eefae6c4a4"
preview_id = "d0901b68a74d4d0cbcf6b837bdd65921"
