name = "scaffold-bbq-smoking"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[kv_namespaces]]
binding = "DATA"
id = "330cbd8fceb843fda7310dd68454b285"
preview_id = "e1f03c3deb5b4bd5a00af6fb50b9837e"
